export const modelRender = `/**
 * <%= info.description; %>
 *
 * OpenAPI spec version: <%= info.version; %>
 * <%= info.contact.email ? "Contact: " + info.contact.email : "";  %>
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
<%- refImportStr;%>
<%= comment; %>export interface <%= title; %> {
<%- interfaceStr; %>
}
`
